### ISSUE TITLE
硬體加速問題

### ISSUE THREAD

**Issue by ChengYen-Tang** [ithinkso117/DotNetPusher#8]
請問你知道要如何設定編碼使用硬體加速嗎?

**Comment by ithinkso117** [comment]
获取codec的时候可以尝试使用qsv编码器，这可以启用intel的硬编码加速

**Comment by ChengYen-Tang** [comment]
https://github.com/ithinkso117/DotNetPusher/blob/8b59ea9f19f972a9cf80b3aa1c9c6e657d969c94/DotNetPusher.Native/Encoder.cpp#L145

您是說這邊嗎?

**Comment by ithinkso117** [comment]
Yes，AV_CODEC_ID_H264 -> AV-CODEC_ID_QSV(应该叫这个，如果没有，进入其源码，搜索QSV)
